name: 'Setup Android build environment'
author: 'Dave Olsthoorn'
description: 'Setup the sdk commandline tools for Android like sdkmanager'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'list'
  color: 'green'
