name: Main CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup local Android problem matchers
      run: |
        ./index.js
    - name: Print example problems
      run: |
        ./test.js
