name: run-test

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - master
      - releases/*
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: setup-android
      - uses: actions/checkout@v2
        with:
          repository: westnordost/StreetComplete
          path: streetcomplete
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Android SDK
        id: 'setup-android'
        uses: ./setup-android/
      - name: Run sdkmanager
        if: runner.os != 'windows'
        run: |
          cd streetcomplete
          ./gradlew build
      - name: Build streetcomplete (Windows)
        if: runner.os == 'windows'
        run: |
          cd streetcomplete
          .\gradlew.bat build
